/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.michelin.kafka.config.providers;

import org.apache.kafka.common.config.ConfigData;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigException;
import org.apache.kafka.common.config.provider.ConfigProvider;
import org.apache.kafka.common.config.types.Password;
import org.apache.kafka.connect.errors.DataException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.crypto.*;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.security.spec.KeySpec;
import java.util.*;

public class AES256ConfigProvider implements ConfigProvider {

    public static final String OVERVIEW_DOC = "A ConfigProvider to decode values encoded with AES256 key.";

    private static final String AES_KEY_CONFIG = "key";
    private static final String SALT_CONFIG = "salt";
    public static final ConfigDef CONFIG_DEF = new ConfigDef()
            .define(AES_KEY_CONFIG, ConfigDef.Type.PASSWORD, ConfigDef.NO_DEFAULT_VALUE,
                    new ConfigDef.NonNullValidator(), ConfigDef.Importance.HIGH,
                    "The AES256 key.")
            .define(SALT_CONFIG, ConfigDef.Type.STRING, ConfigDef.NO_DEFAULT_VALUE,
                    new ConfigDef.NonEmptyString(), ConfigDef.Importance.HIGH,
                    "The AES256 salt.");



    private Cipher cipher;

    @Override
    public void configure(Map<String, ?> configs) {
        Map<String, Object> parsedConfigs = CONFIG_DEF.parse(configs);
        Password aesKey = (Password) parsedConfigs.get(AES_KEY_CONFIG);
        String salt = parsedConfigs.get(SALT_CONFIG).toString();
        try {
            byte[] iv = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
            IvParameterSpec ivspec = new IvParameterSpec(iv);

            SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
            KeySpec spec = new PBEKeySpec(aesKey.value().toCharArray(), salt.getBytes(), 65536, 256);
            SecretKey tmp = factory.generateSecret(spec);
            SecretKeySpec secretKey = new SecretKeySpec(tmp.getEncoded(), "AES");

            cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.DECRYPT_MODE, secretKey, ivspec);
        } catch (Exception e) {
            throw new ConfigException("Error during initialization", e);
        }
    }

    @Override
    public ConfigData get(String path) {
        return new ConfigData(new HashMap<>());
    }

    @Override
    public ConfigData get(String path, Set<String> keys) {

        Map<String,String> decoded = new HashMap<>();

        keys.forEach(key -> {
            try {
                decoded.put(key, new String(cipher.doFinal(Base64.getDecoder().decode(key))));
            } catch (Exception e) {
                throw new DataException("Error while decrypting " + key, e);
            }
        });

        return new ConfigData(decoded);
    }

    @Override
    public void close() throws IOException {

    }

}
