/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.michelin.kafka.config.providers;

import org.apache.kafka.common.config.ConfigData;
import org.apache.kafka.common.config.ConfigDef;
import org.apache.kafka.common.config.ConfigException;
import org.apache.kafka.common.config.provider.ConfigProvider;
import org.apache.kafka.common.config.types.Password;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * AES256 encrypted Kafka config provider.
 *
 * @author Michelin
 */
public class AES256ConfigProvider implements ConfigProvider {
    public static final String OVERVIEW_DOC = "A ConfigProvider to decode values encoded with AES256 key.";

    private static final String AES_KEY_CONFIG = "key";
    private static final String SALT_CONFIG = "salt";

    /**
     * Definition of accepted parameters: key and salt.
     */
    public static final ConfigDef CONFIG_DEF = new ConfigDef()
            .define(AES_KEY_CONFIG, ConfigDef.Type.PASSWORD, ConfigDef.NO_DEFAULT_VALUE,
                    new ConfigDef.NonNullValidator(), ConfigDef.Importance.HIGH, "The AES256 key.")
            .define(SALT_CONFIG, ConfigDef.Type.STRING, ConfigDef.NO_DEFAULT_VALUE,
                    new ConfigDef.NonEmptyString(), ConfigDef.Importance.HIGH, "The AES256 salt.");

    /**
     * Represents the aes256 key
     */
    private Password aesKey;

    /**
     * Represents the aes256 salt
     */
    private String salt;

    @Override
    public void configure(final Map<String, ?> pConfigs) {
        final var parsedConfigs = CONFIG_DEF.parse(pConfigs);
        this.aesKey = (Password) parsedConfigs.get(AES_KEY_CONFIG);
        this.salt = parsedConfigs.get(SALT_CONFIG).toString().trim();
    }

    @Override
    public ConfigData get(final String pPath) {
        return new ConfigData(new HashMap<>());
    }

    @Override
    public ConfigData get(final String pPath, final Set<String> pKeys) {
        final var decoded = new HashMap<String, String>();
        final var cipher = this.getCipher();
        pKeys.forEach(key -> {
            try {
                decoded.put(key, new String(cipher.doFinal(Base64.getDecoder().decode(key)), StandardCharsets.UTF_8));
            } catch (IllegalArgumentException | IllegalBlockSizeException | BadPaddingException e) {
                throw new ConfigException("Error while decrypting " + key, e);
            }
        });

        return new ConfigData(decoded);
    }

    @Override
    public void close() {
        // nothing to destroy while closing the config provider.
    }

    /**
     * Gets the cipher instance for decryption.
     *
     * @return The cipher used to decrypt the keys.
     */
    private Cipher getCipher() {
        try {
            final var ivspec = new IvParameterSpec(new byte[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});

            final var factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
            final var spec = new PBEKeySpec(this.aesKey.value().toCharArray(), this.salt.getBytes(StandardCharsets.UTF_8), 65536, 256);
            final var tmp = factory.generateSecret(spec);
            final var secretKey = new SecretKeySpec(tmp.getEncoded(), "AES");

            final var cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.DECRYPT_MODE, secretKey, ivspec);
            return cipher;
        } catch (final Exception e) {
            throw new ConfigException("Error during Cipher initialization", e);
        }
    }
}
